version: '2.15.1'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=W1A6-kSNY0LSH1rTc9t47YrWgeVm91HH5r7RS9X-Trn5N8n9zR8"
  db:
    image: postgres:12
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
